language: node_js
node_js:
 - "node"
notifications:
    email:
        recipients:
            - gimmysu@gmail.com
        on_success: always
        on_failure: always
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
  - npm run test:prod
