language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
notifications:
    email:
        recipients:
            - gimmysu@gmail.com
        on_success: always
        on_failure: always
        notifications:
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/78f53988cc8db6f8d635
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
ignore:
  - *.md
  - doc/*
  
script:
  - echo 'Build starts!!'
  - echo 'Testing!'
  - npm -v
